/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cloud_logic_custom": [
        {
            "name": "AdminQueries",
            "endpoint": "https://0h232hoecc.execute-api.us-east-1.amazonaws.com/huskyenv",
            "region": "us-east-1"
        },
        {
            "name": "testapi",
            "endpoint": "https://eb6or8lzdb.execute-api.us-east-1.amazonaws.com/huskyenv",
            "region": "us-east-1"
        }
    ],
    "aws_cognito_identity_pool_id": "us-east-1:807d1973-f216-4fde-a688-0af609cac922",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_uIk4Nu15F",
    "aws_user_pools_web_client_id": "5fmo292ol5mqkss3ig1kd11ofs",
    "oauth": {},
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OPTIONAL",
    "aws_cognito_mfa_types": [
        "SMS",
        "TOTP"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ]
};


export default awsmobile;
